import { NextRequest, NextResponse } from 'next/server';
import { Resend } from 'resend';
import { createClient } from '@supabase/supabase-js';

// Initialize Resend lazily to avoid build errors if env var is missing
const getResend = () => {
  const apiKey = process.env.RESEND_API_KEY;
  if (!apiKey) {
    throw new Error('Missing RESEND_API_KEY');
  }
  return new Resend(apiKey);
};
const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!
);

export async function POST(request: NextRequest) {
  try {
    const { participantId, email } = await request.json();

    if (!participantId || !email) {
      return NextResponse.json(
        { error: 'Participant ID and email are required' },
        { status: 400 }
      );
    }

    // Validate email format
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    if (!emailRegex.test(email)) {
      return NextResponse.json(
        { error: 'Invalid email format' },
        { status: 400 }
      );
    }

    // Get participant details
    const { data: participant, error: participantError } = await supabase
      .from('participants')
      .select('*, events(*)')
      .eq('id', participantId)
      .single();

    if (participantError || !participant) {
      return NextResponse.json(
        { error: 'Participant not found' },
        { status: 404 }
      );
    }

    // Get assignment
    const { data: assignment, error: assignmentError } = await supabase
      .from('assignments')
      .select('*, receiver:receiver_id(*)')
      .eq('giver_id', participantId)
      .single();

    if (assignmentError || !assignment) {
      return NextResponse.json(
        { error: 'Assignment not found' },
        { status: 404 }
      );
    }

    const event = participant.events;
    const receiver = assignment.receiver;

    // Build email content
    const baseUrl = process.env.NEXT_PUBLIC_APP_URL || 'http://localhost:3000';
    const personalLink = `${baseUrl}/event/${event.id}/join?token=${participant.token}`;

    const emailHtml = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; padding: 20px;">
  <div style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); padding: 30px; text-align: center; border-radius: 10px 10px 0 0;">
    <h1 style="color: white; margin: 0; font-size: 28px;">🎁 Your Secret Santa Assignment</h1>
  </div>

  <div style="background: #f9f9f9; padding: 30px; border-radius: 0 0 10px 10px;">
    <h2 style="color: #667eea; margin-top: 0;">Hi ${participant.name}!</h2>

    <p>You're participating in <strong>${event.group_name}</strong>!</p>

    <div style="background: white; padding: 25px; border-radius: 8px; margin: 25px 0; border-left: 4px solid #667eea; text-align: center;">
      <p style="font-size: 14px; color: #666; margin: 0 0 10px 0;">You are Secret Santa for:</p>
      <h2 style="color: #667eea; margin: 10px 0; font-size: 32px;">🎅 ${receiver.name}</h2>
    </div>

    <div style="background: white; padding: 20px; border-radius: 8px; margin: 20px 0; border-left: 4px solid #764ba2;">
      <h3 style="margin-top: 0; color: #764ba2;">📅 Event Details</h3>
      <ul style="padding-left: 20px; margin: 10px 0;">
        <li><strong>Exchange Date:</strong> ${new Date(event.exchange_date).toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })}</li>
        <li><strong>Budget:</strong> $${event.budget_amount}</li>
      </ul>
      ${event.custom_message ? `<p style="margin: 15px 0 0 0; padding: 15px; background: #f5f5f5; border-radius: 6px; font-style: italic;">"${event.custom_message}"</p>` : ''}
    </div>

    <div style="background: white; padding: 20px; border-radius: 8px; margin: 20px 0; border-left: 4px solid #f59e0b;">
      <h3 style="margin-top: 0; color: #f59e0b;">🔗 Your Personal Link</h3>
      <p style="margin: 10px 0;">Access your assignment anytime:</p>
      <a href="${personalLink}" style="display: inline-block; padding: 12px 24px; background: #f59e0b; color: white; text-decoration: none; border-radius: 6px; margin: 10px 0;">View Assignment</a>
      <p style="font-size: 12px; color: #666; word-break: break-all;">${personalLink}</p>
    </div>

    <div style="background: #fff3cd; padding: 15px; border-radius: 6px; margin: 20px 0; border: 1px solid #ffc107;">
      <p style="margin: 0; color: #856404;"><strong>🤫 Remember:</strong> Keep your assignment secret! The magic of Secret Santa is in the surprise.</p>
    </div>

    <p style="font-size: 14px; color: #666; margin-top: 30px;">Happy gifting! 🎄</p>
  </div>

  <div style="text-align: center; padding: 20px; font-size: 12px; color: #999;">
    <p>Generated by <a href="${baseUrl}" style="color: #667eea; text-decoration: none;">Secret Santa Generator</a></p>
  </div>
</body>
</html>
`;

    // Send email using Resend
    const resend = getResend();
    const { data, error } = await resend.emails.send({
      from: 'Secret Santa <noreply@secret-santa-generator.net>',
      to: [email],
      subject: `Join our gift exchange: ${event.group_name}`,
      html: emailHtml,
    });

    if (error) {
      console.error('Resend error:', error);
      return NextResponse.json(
        { error: 'Failed to send email' },
        { status: 500 }
      );
    }

    // Update participant email and email_sent status in database
    await supabase
      .from('participants')
      .update({
        email: email,
        email_sent: true
      })
      .eq('id', participantId);

    return NextResponse.json({
      success: true,
      emailId: data?.id
    });

  } catch (error) {
    console.error('Error sending participant email:', error);
    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 }
    );
  }
}
